import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Toastprovider from "../components/ui/provider/Toaster-provider";
import "@uploadthing/react/styles.css";

export const metadata = {
  title: "LMS Project",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body className={` antialiased`}>
          <Toastprovider />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
